version: "3.3"
services:
  web:
    build: .
    environment:
        - USER_NAME=ghosh
        - PASSWORD=ghosh
        - STATIC_FILE_PATH=/app/static-files
        - GIN_MODE=release
    ports:
        - 8000:8080