name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "file-server" #Must be unique in Heroku
          heroku_email: "kakanghosh69@gmail.com"
          usedocker: true
        env:
          USER_NAME: ${{ secrets.FILE_SERVER_USER_NAME }}
          PASSWORD: ${{ secrets.FILE_SERVER_PASSWORD }}
          GIN_MODE: release
          STATIC_FILE_PATH: /app/static-files